headers = {
    'Accept': 'application/json, text/plain, */*',
    'Accept-Language': 'en-GB,en;q=0.9,en-US;q=0.8,pl;q=0.7,nl;q=0.6',
    'Authorization': 'Atmosphere atmosphere_app_id=kingfisher-LTbGHXKinHaJSV86nEjf0KnO70UOVE6UcYAswLuC',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'Origin': 'https://www.trade-point.co.uk',
    'Pragma': 'no-cache',
    'Referer': 'https://www.trade-point.co.uk/',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'cross-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
    'X-Context-Location': '/kitchen/kitchen-cabinets/kitchen-doors.cat',
    'sec-ch-ua': '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'x-dtc': 'sn="v_4_srv_-2D20_sn_3DVN1BO5L1CBBVKHKCI1EI1OPMMJFPCD", pc="-20$218348505_48h39vCMRFHLTDBVQCPNAPAHBUKCANTLTWOTFH-0e0", v="17112790819981S31G3BNLBCJ3II45KG52PONU7NP0H1A", app="d09643a9157f0c88", r="https://www.trade-point.co.uk/kitchen/kitchen-cabinets/kitchen-doors.cat?Brand=GoodHome&Range=Stevia"',
    'x-tenant': 'TPUK',
}